name: Meme Generator Github Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repozitorij
        uses: actions/checkout@v3

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker verzija
        run: docker --version

      - name: Preverjanje Docker Build
        run: docker build . --file Dockerfile --tag meme-generator:latest